[package]
name = "sudoku"
version = "0.1.0"
edition = "2021"

[lib]
name ="sudoku"
path = "src/lib.rs"

[[bin]]
name = "sudoku_bin"
path = "src/bin.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
